name: Doctorchat Partners PROD CI/CD
on:
  push:
    branches:
      - main
jobs:

  Deploying:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Connection
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~
            chmod +x reload-partners
            ./reload-partners
            echo "✅✅✅ Application deployed!"

          host: '31.172.77.196'
          user: 'doctorchat-partners'
          pass: ${{ secrets.APP_PASSWORD }}
